apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gitopswebtest
  name: gitopswebtest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitopswebtest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gitopswebtest
    spec:
      containers:
      - image: ltartsmusic/gitopstest:29
        name: gitopswebtest
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: gitopswebtest
 ---
 apiVersion: v1
kind: Ingress
metadata:
  name: test-ingress
spec:
  defaultBackend:
    service: lb-service
      name: test
      port:
        number: 80
