apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: awsgitopswebtest
  name: awsgitopswebtest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: awsgitopswebtest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: awsgitopswebtest
    spec:
      containers:
      - image: ltartsmusic/awsgitopswebtest:8
        name: awsgitopswebtest
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: awsgitopswebtest
