apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gitopswebproject
  name: gitopswebproject
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitopswebproject
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gitopswebproject
    spec:
      containers:
      - image: ltartsmusic/gitopswebproject:latest
        name: gitopswebproject
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: gitopswebproject
